export interface NHLTeam {
  label: string;
  value: string;
  timezone: string;
}

export const NHL_TEAMS: NHLTeam[] = [
  { label: "Anaheim Ducks", value: "ANA", timezone: "America/Los_Angeles" },
  { label: "Boston Bruins", value: "BOS", timezone: "America/New_York" },
  { label: "Buffalo Sabres", value: "BUF", timezone: "America/New_York" },
  { label: "Calgary Flames", value: "CGY", timezone: "America/Edmonton" },
  { label: "Carolina Hurricanes", value: "CAR", timezone: "America/New_York" },
  { label: "Chicago Blackhawks", value: "CHI", timezone: "America/Chicago" },
  { label: "Colorado Avalanche", value: "COL", timezone: "America/Denver" },
  { label: "Columbus Blue Jackets", value: "CBJ", timezone: "America/New_York" },
  { label: "Dallas Stars", value: "DAL", timezone: "America/Chicago" },
  { label: "Detroit Red Wings", value: "DET", timezone: "America/New_York" },
  { label: "Edmonton Oilers", value: "EDM", timezone: "America/Edmonton" },
  { label: "Florida Panthers", value: "FLA", timezone: "America/New_York" },
  { label: "Los Angeles Kings", value: "LAK", timezone: "America/Los_Angeles" },
  { label: "Minnesota Wild", value: "MIN", timezone: "America/Chicago" },
  { label: "Montreal Canadiens", value: "MTL", timezone: "America/Montreal" },
  { label: "Nashville Predators", value: "NSH", timezone: "America/Chicago" },
  { label: "New Jersey Devils", value: "NJD", timezone: "America/New_York" },
  { label: "New York Islanders", value: "NYI", timezone: "America/New_York" },
  { label: "New York Rangers", value: "NYR", timezone: "America/New_York" },
  { label: "Ottawa Senators", value: "OTT", timezone: "America/New_York" },
  { label: "Philadelphia Flyers", value: "PHI", timezone: "America/New_York" },
  { label: "Pittsburgh Penguins", value: "PIT", timezone: "America/New_York" },
  { label: "San Jose Sharks", value: "SJS", timezone: "America/Los_Angeles" },
  { label: "Seattle Kraken", value: "SEA", timezone: "America/Los_Angeles" },
  { label: "St. Louis Blues", value: "STL", timezone: "America/Chicago" },
  { label: "Tampa Bay Lightning", value: "TBL", timezone: "America/New_York" },
  { label: "Toronto Maple Leafs", value: "TOR", timezone: "America/Toronto" },
  { label: "Utah Mammoth", value: "UTA", timezone: "America/Denver" },
  { label: "Vancouver Canucks", value: "VAN", timezone: "America/Vancouver" },
  { label: "Vegas Golden Knights", value: "VGK", timezone: "America/Los_Angeles" },
  { label: "Washington Capitals", value: "WSH", timezone: "America/New_York" },
  { label: "Winnipeg Jets", value: "WPG", timezone: "America/Winnipeg" },
];

export const APPROVED_NHL_SUBREDDITS: string[] = [
  "nhl",
  "hockey",
  "AnaheimDucks",
  "BostonBruins",
  "sabres",
  "canes",
  "BlueJackets",
  "CalgaryFlames",
  "hawks",
  "ColoradoAvalanche",
  "DallasStars",
  "DetroitRedWings",
  "EdmontonOilers",
  "FloridaPanthers",
  "losangeleskings",
  "wildhockey",
  "Habs",
  "devils",
  "NashvillePredators",
  "NewYorkIslanders",
  "rangers",
  "OttawaSenators",
  "Flyers",
  "penguins",
  "SeattleKraken",
  "SanJoseSharks",
  "stlouisblues",
  "TampaBayLightning",
  "leafs",
  "Utah_Hockey",
  "canucks",
  "goldenknights",
  "winnipegjets",
  "caps",
]

export function getTeamTimezone(teamAbbrev: string): string | undefined {
  return NHL_TEAMS.find(team => team.value === teamAbbrev)?.timezone;
}