export const NHL_TEAMS = [
  { label: "Anaheim Ducks", value: "ANA" },
  { label: "Boston Bruins", value: "BOS" },
  { label: "Buffalo Sabres", value: "BUF" },
  { label: "Calgary Flames", value: "CGY" },
  { label: "Carolina Hurricanes", value: "CAR" },
  { label: "Chicago Blackhawks", value: "CHI" },
  { label: "Colorado Avalanche", value: "COL" },
  { label: "Columbus Blue Jackets", value: "CBJ" },
  { label: "Dallas Stars", value: "DAL" },
  { label: "Detroit Red Wings", value: "DET" },
  { label: "Edmonton Oilers", value: "EDM" },
  { label: "Florida Panthers", value: "FLA" },
  { label: "Los Angeles Kings", value: "LAK" },
  { label: "Minnesota Wild", value: "MIN" },
  { label: "Montreal Canadiens", value: "MTL" },
  { label: "Nashville Predators", value: "NSH" },
  { label: "New Jersey Devils", value: "NJD" },
  { label: "New York Islanders", value: "NYI" },
  { label: "New York Rangers", value: "NYR" },
  { label: "Ottawa Senators", value: "OTT" },
  { label: "Philadelphia Flyers", value: "PHI" },
  { label: "Pittsburgh Penguins", value: "PIT" },
  { label: "San Jose Sharks", value: "SJS" },
  { label: "Seattle Kraken", value: "SEA" },
  { label: "St. Louis Blues", value: "STL" },
  { label: "Tampa Bay Lightning", value: "TBL" },
  { label: "Toronto Maple Leafs", value: "TOR" },
  { label: "Vancouver Canucks", value: "VAN" },
  { label: "Vegas Golden Knights", value: "VGK" },
  { label: "Washington Capitals", value: "WSH" },
  { label: "Winnipeg Jets", value: "WPG" },
  { label: "Utah Hockey Club", value: "UTA" },
];